Remove operator '+' which is already provided by _ExtensibleCollectionType:
error: ambiguous use of operator '+'
                                 ^
Swift.+:1:6: note: found this candidate
func +<EC1 : _ExtensibleCollectionType, EC2 : _ExtensibleCollectionType
where EC1.Generator.Element == EC1.Generator.Element>(lhs: EC1, rhs:
EC2) -> EC1
     ^
Set.+:1:6: note: found this candidate
func +<S : SequenceType>(set: Set<S.Generator.Element>, sequence: S) ->
Set<S.Generator.Element>